blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ æé—®ä¸åˆ†äº«
    url: https://github.com/tools-js-cn/demo1/discussions/categories/q-a
    about: åœ¨æ­¤æå‡ºé—®é¢˜å’Œåˆ†äº«ä½ çš„è§£å†³æ–¹æ¡ˆâ†’
